### PR TITLE
read station netcdf dsg

### PR DESCRIPTION
**Pull request by dblodgett-usgs**
See function details for description. 

I'm not sure the list format is the right response, but it gets the job done. 

I've not tested this against files that have multiple variables in them, but theoretically it will work. Will add a test for such a file some time and make sure it functions.

Note that ncdf has strange handling of coordinate variables, time isn't a variable... this is ok, it's just odd.

### CODE REVIEW

**Comment by dblodgett-usgs** [comment]
@jwalker-usgs This is worth you giving a quick review if you have a sec.

**Comment by dblodgett-usgs** [comment]
@lawinslow @jiwalker-usgs Have you had a chance to look at this? I'm pretty much closing out of this work and think we should get it into the base repo.

**Comment by jiwalker-usgs** [comment]
It looks ok to me (haven't been following this work too closely.  The one thing I'd say is that the function is pretty big and doing a lot of stuff.  It would probably be a useful exercise at some point to split it up into components so that it is easier understand what is all going on.

**Comment by dblodgett-usgs** [comment]
Agreed. I think a refactor is warranted soon now that we have a basic read/write done. I want to bring in some smarts from the climates package too, but those utilities need to be refactored too....

**Comment by dblodgett-usgs** [comment]
Going to merge this so I can commit some new stuff.

**Comment by dblodgett-usgs** [comment]
Doh... I don't have merge rights. once more PR coming.

**Comment by lawinslow** [comment]
@dblodgett-usgs didn't realize you don't have write permission. Added.

**Pull request merged**
